### PR TITLE
chore: use type import&export

### PR DESCRIPTION
**Pull request by ajuner**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [x] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

代码警告要用type
用lint把代码都更新了下
把prettier更新了不然在lint时会报错

### CODE REVIEW

**Comment by tangjinzhou** [comment]
?   lint 规则改了   怎么那么多改动

**Comment by ajuner** [comment]
我再调调

**Comment by ajuner** [comment]
这个警告
mmexport1615123918100
我再调调直接用lint fix规则好像有点问题..

**Comment by ajuner** [comment]
箭头函数参数的括号去掉了，function后面的这个空格是个问题。。

**Comment by zkwolf** [comment]
看上去比较无解了，prettier2默认了function后面加空格，[prettier2](https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot)

**Pull request closed without merging**
