### PR TITLE
fix: fix typescript version limit

### PR DESCRIPTION
**Pull request by mehunk**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

1. 今天在编译的时候一直在报 ts 文件编译的错误，后来试了几次发现应该是 4.4.0 以上版本的 breaking changes 影响了现有的代码，所以对 package.json 里面的 typescript 依赖版本做了限制，如果马上要对代码中 ts 的定义进行修复和升级的话就不用管这个 pr 了。

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Review by Amour1688 — APPROVED** [review]

**Comment by Amour1688** [comment]
具体报啥错误贴一下吧

**Comment by tangjinzhou** [comment]
我先 merge 了  ，可以 run compile  看一下

**Comment by tangjinzhou** [comment]
@Amour1688

**Comment by mehunk** [comment]
> 具体报啥错误贴一下吧

直接在 github 上看这两天的 pr 提交以后 ci 跑的错误就行，一堆错误，可能是这个版本 lib.dom.d.ts 改动比较大吧

**Pull request merged**
