### PR TITLE
Updated translation file for Danish language

### PR DESCRIPTION
**Pull request by pioka1**
### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [x] Other (Translation update)

### What's the background?

> 1. Describe the source of requirement.
Translation file for Danish was out-of-date compared to English default translation file
> 2. Resolve what problem.
Missing translations
> 3. Related issue link.
No issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by pioka1** [comment]
Should target branch be `master`?

**Comment by tangjinzhou** [comment]
you can copy https://github.com/ant-design/ant-design/blob/master/components/locale/da_DK.tsx   
We will synchronize language packs regularly from https://github.com/ant-design/ant-design/tree/master/components/locale

**Comment by tangjinzhou** [comment]
> Should target branch be `master`?

we will use `main` branch

**Comment by pioka1** [comment]
I will make a new PR against the main `ant-design` repository with the translation

**Pull request closed without merging**
