### PR TITLE
perf[table]: replace `eagerComputed` with `computed` 

### PR DESCRIPTION
**Pull request by cc-hearts**
Relates #7592.

In Vue 3.4+, if computed new value does not change,`computed`, `effect`, `watch`, `watchEffect`, `render` dependencies will not be triggered.

### CODE REVIEW

**Comment by orionna319** [comment]
Have you tried it locally? When I use `pnpm patch` to patch `/vc-table/Cell/index.tsx`, I use computed instead of eagerComputed, but I still get the error `Maximum call stack size exceeded`

**Comment by cc-hearts** [comment]
I've tested it locally and it works, is the package for the `pnpm patch` a `tsx` file? But if you import locally, it will import the files in the `es` folder after compiling, if there is still a problem, can you provide me with the code?

**Comment by orionna319** [comment]
I used pnpm patch under `node_modules/ant-design-vue/lib/vc-table/Cell/index.js`. Maybe I need to patch `node_modules/ant-design-vue/es/vc-table/Cell/index.js`. I will try it again tomorrow. Thank you for your reply.

**Comment by cc-hearts** [comment]
image

Here's my test in vite's development environment(I have not yet executed the patch operation, just directly changed the third-party code, if there is a problem, I will continue to correct it!)

**Comment by orionna319** [comment]
I should patch in `node_modules/ant-design-vue/es/vc-table/Cell/index.js`. Thank you for your contribution. I just tested it locally and there is no error. Thank you.

**Comment by cc-hearts** [comment]
refs: #7682

**Pull request closed without merging**
