### PR TITLE
refactor(progress): refactor progress component with typescript

### PR DESCRIPTION
**Pull request by Xutaotaotao**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [X] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by Xutaotaotao** [comment]
官网所有例子已经测试通过了。

**Comment by Amour1688** [comment]
冲突了

**Comment by Xutaotaotao** [comment]
什么冲突了 @Amour1688 ，合并代码冲突了？还是和别人写的冲突了。

**Comment by Amour1688** [comment]
解决一下冲突，不然没发合并

**Comment by Xutaotaotao** [comment]
冲突已解决，看看还有没有问题 @Amour1688 ，change变多了，好像是提交的时候自带格式化了代码。

**Comment by Amour1688** [comment]
`progress` 的单测跑不起来。。。

**Comment by Amour1688** [comment]
https://github.com/vueComponent/ant-design-vue/commit/c97af1ac1852e01359048c0e463852ef451e3075

**Comment by Xutaotaotao** [comment]
。。。merge过后就不通了，解决冲突后搞忘跑单测了。。。现在改了一下，结果你已经改了。。。。 @Amour1688

**Pull request closed without merging**
