### PR TITLE
Update ValidationRule message type

### PR DESCRIPTION
**Pull request by pastr**
### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

The type of message comes from the library async-validator and it has been updated: https://github.com/yiminghe/async-validator/pull/251/files
This PR is to keep ant-design-vue up to date with that change.

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by tangjinzhou** [comment]
but how to use func for message?
if user use func, how to render message?

**Comment by pastr** [comment]
You can already use it, it was just the type that wasn't up to date
You can see a basic example here: https://codesandbox.io/s/brave-microservice-gjb5y?file=/src/components/form-model-example.vue 
The rules for name and region are using a function. 
It's also useful when using vue-i18n, the doc of async-validator has a small example here:
https://github.com/yiminghe/async-validator#messages
Hopefully, this answers your questions :)

**Comment by tangjinzhou** [comment]
👍   I got it, thank you for you pr.

**Comment by pastr** [comment]
Thanks for your work!

**Pull request merged**
