### PR TITLE
perf: find parent component when only secondary component used in demo

### PR DESCRIPTION
**Pull request by Amour1688**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Import Primary component when only secondary component used in demo

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by tangjinzhou** [comment]
没看到这个pr，就直接merge master，并且做了改动  😓  要不你再master上在提交一个pr ？

**Comment by Amour1688** [comment]
> 没看到这个pr，就直接merge master，并且做了改动 😓 要不你再master上在提交一个pr ？
改到master上了

**Comment by Amour1688** [comment]
> 没看到这个pr，就直接merge master，并且做了改动 😓 要不你再master上在提交一个pr ？

改到master上了

**Comment by tangjinzhou** [comment]
有冲突

**Pull request merged**
