### PR TITLE
chore: v1 support vite

### PR DESCRIPTION
**Pull request by xunuo0x**
### This is a ...

-  New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. description: change moment import, and v1 support vite
> 2. issue link https://github.com/vueComponent/ant-design-vue/issues/4722

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by xunuo0x** [comment]
@tangjinzhou 请问可以合入了吗 🤔️

**Comment by tangjinzhou** [comment]
moment 是没有默认导出的   对部分用户应该是有影响的
如果用vite，是不是可以尝试用 cdn？或 alias 等等   或者给写个插件？

**Comment by tangjinzhou** [comment]
> 这样的话，v2版本的导入方式也存在问题？ [fbcf0bf](https://github.com/vueComponent/ant-design-vue/commit/fbcf0bff9d9e8ea7e6bd26e2a699e69e043f7a8e) 这是之前支持 vite 的提交

因为是大版本升级，V2 不需要考虑历史用户问题

**Comment by carl-jin** [comment]
> @tangjinzhou 请问可以合入了吗 🤔️

最终解决方案是什么

**Comment by carl-jin** [comment]
https://github.com/carl-jin/vite-plugin-antdv1-momentjs-resolver
写了小插件, 解决了这个问题

**Comment by 1291927234** [comment]
那个插件对版本有什么要求吗，我用这不行嘞

**Pull request closed without merging**
