### PR TITLE
style: decrease @text-color contrast

### PR DESCRIPTION
**Pull request by zkwolf**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [x] Other (about what?)

### What's the background?

> 1. Describe the source of requirement
降低text-color对比度，防止某些情况下瞎眼
image
如图所示，降低对比度后在黑暗模式下依然达到了AAA
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by tangjinzhou** [comment]
你这个有点暴力了

**Comment by zkwolf** [comment]
要不然我去ant design那边提一嘴，我觉得他们pro和官网直接替换变量也挺暴力的，这样示例和自己import出来的结果就是两个颜色了

**Comment by tangjinzhou** [comment]
> 要不然我去ant design那边提一嘴，我觉得他们pro和官网直接替换变量也挺暴力的，这样示例和自己import出来的结果就是两个颜色了

可以

**Comment by tangjinzhou** [comment]
什么结论 ？

**Comment by zkwolf** [comment]
https://github.com/ant-design/ant-design/issues/29265

**Pull request closed without merging**
