### PR TITLE
fix: onSelect error capture issue

### LINKED ISSUE #5204: Error Capture Issue
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
MacOS 11.4, Chrome 97.0.4692.71, Vue 3.2.28

### Reproduction link
[https://github.com/gaokun/antdv-error-tracker](https://github.com/gaokun/antdv-error-tracker)

### Steps to reproduce
1. select an option [trigger 'onSelect']
2. then you can find 'Uncaught (in promise) test error' in console

see detail in reproduction demo

### What is expected?
'onSelect' of Select should fire onErrorCaptured

### What is actually happening?
it dosen't

image

---
### I am not sure this is a bug or wrong usage.

If it is indeed a bug, it exsits in everywhere we invoke callbacks like this way 'props.onSelect()', it breaks the promise chain.

I am free to any feedback.
Thx
Ken

### PR DESCRIPTION
**Pull request by gaokun**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?
Please refer to #5204 

Test case provided.
> error thrown in [onSelect]

image

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
No
> 2. What will say in changelog?
support promise rejection for event callback
> 3. Does this PR contains potential break change or other risk?
No

### Additional Plan? (Optional if not new feature)
This is a demo PR about how to fix #5204 .
It's supposed not to be merged for now.
We need to decide how to do that after code review.

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by tangjinzhou** [comment]
why not use emit

**Comment by gaokun** [comment]
As I mentioned in #5204 

> `emit` is asynchronous, and wouldn't break main process if error happen. 
>
> Example:
> 
> ```js
> function onClick() {
>   emit('custom-event', 'reject error');
>   console.log('this message will show before onErrorCaptured, and it always show up no matter emit fires error or not');
> }
> ```

it will be involved in potential risk

**Comment by tangjinzhou** [comment]
In this case, the modification cost is too high.

**Comment by gaokun** [comment]
Yes, it would be.
`Select` is a complex base component, there are lots of callbacks inside.

Like: 
```js
    const onInternalSearchSplit: BaseSelectProps['onSearchSplit'] = words => {
      let patchValues: RawValueType[] = words;

      if (props.mode !== 'tags') {
        patchValues = words
          .map(word => {
            const opt = labelOptions.value.get(word);
            return opt?.value;
          })
          .filter(val => val !== undefined);
      }

      const newRawValues = Array.from(new Set<RawValueType>([...rawValues.value, ...patchValues]));
      triggerChange(newRawValues);
      newRawValues.forEach(newRawValue => {
        triggerSelect(newRawValue, true);    // <=======  callbak in forEach
      });
    };
```

But I think it is necessary.
It it all about tradeoff, I just put it on the table, and up to you surely.

**Comment by gaokun** [comment]
Yes, it would be.
`Select` is a complex base component, there are lots of callbacks inside.

Like: 
```js
    const onInternalSearchSplit: BaseSelectProps['onSearchSplit'] = words => {
      let patchValues: RawValueType[] = words;

      if (props.mode !== 'tags') {
        patchValues = words
          .map(word => {
            const opt = labelOptions.value.get(word);
            return opt?.value;
          })
          .filter(val => val !== undefined);
      }

      const newRawValues = Array.from(new Set<RawValueType>([...rawValues.value, ...patchValues]));
      triggerChange(newRawValues);
      newRawValues.forEach(newRawValue => {
        triggerSelect(newRawValue, true);    // <=======  callbak in forEach
      });
    };
```

But I think it is necessary.
It it all about tradeoff, I just put it on the table, and up to you surely.

**Pull request closed without merging**
