### PR TITLE
Add capability to FormModel component, to validate part of the fields while still getting a Promise in return

### PR DESCRIPTION
**Pull request by athrunsun**
[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?
- I need to validate part of the fields and expect a `Promise` as return value.
- `FormModel.validate()` supports returning a promise, but doesn't support validating part of the fields. From my understanding, this method is to get a final result against all fields' validity.
- `FormModel.validateField()` supports validating part of the fields, but doesn't support returning a promise. From my understanding, this method is to apply a callback to each of the fields passed in.

### API Realization
My original goal is to get a final result against **part of the fields' validity**, thus refactoring `FormModel.validate()` is my choice.

I added a second parameter to this method, making it `validate(callback, fieldProps)`. In order to avoid a destructive refactoring, I put `fieldProps` at the 2nd position - inserting it at the 1st position will break this method's backward compatibility, which is unacceptable IMO.

### What's the effect?
Now I can validate just part of the form fields while still getting a `Promise` in return,

```js
const valid = await this.$refs.dataForm.validate(undefined, ['fieldProp1', 'fieldProp2']);
```

### Changelog description
1. English description
> Add a second parameter `fieldProps` to `FormModel.validate()` to support validating part of the form fields and get a `Promise` in return.

2. Chinese description (optional)
> 给 `FormModel.validate()` 增加第二个参数 `fieldProps` 以支持验证部分字段的同时也能获得一个 `Promise` 作为返回值。

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [x] Demo is not needed
- [x] TypeScript definition is updated/provided
- [x] Changelog is provided

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by athrunsun** [comment]
One question: where can I update the documentation site?

**Comment by tangjinzhou** [comment]
If the pr is accepted, we will add related documents, thanks pr

**Comment by tangjinzhou** [comment]
这里还是建议把 fields 放在第一个参数，函数内部可以根据参数类型来去兼容之前api，不会破坏使用  
另外 2.0 版本会进行比较大的重构

**Comment by athrunsun** [comment]
> 这里还是建议把 fields 放在第一个参数，函数内部可以根据参数类型来去兼容之前api，不会破坏使用
> 另外 2.0 版本会进行比较大的重构

如果是这样的话，我还是等等2.0版本吧。1.x版本我自己想想其它办法。

**Pull request closed without merging**
